server:
  port: 8080

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: greetings
          binder: rabbit
        output:
          destination: response
          binder: rabbit
          contentType: application/json
