server:
  port: 8000

spring:
  cloud:
    stream:
      bindings:
        output:
          binder: rabbit
          destination: greetings
          contentType: application/json
        input:
          binder: rabbit
          destination: response
          